name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.1']
    services:
      # Label used to access the service container
      db:
        # Docker Hub image
        image: postgres:15-alpine
        # Provide the password for postgres
        env:
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
          POSTGRES_DB: google_scraping_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: cd backend && bundle install
      - name: setup database
        env:
            RAILS_ENV: test
            POSTGRES_HOST: db
            POSTGRES_DB: google_scraping_test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        run: cd backend && bundle exec rails db:create db:migrate
      - name: Run tests
        env:
          RAILS_ENV: test
          POSTGRES_HOST: db
          POSTGRES_DB: google_scraping_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: cd backend && bundle exec rspec spec
